### ISSUE TITLE
healthcheck for tansu

### ISSUE THREAD

**Issue by xmlking** [tansu-io/tansu#290]
can you add healthcheck for tansu?
I want to run redpanda console after tansu is up

```yaml
  console:
    image: redpandadata/console:v3.1.0
    hostname: console
    container_name: console
    environment:
      KAFKA_BROKERS: 'tansu:9092'
      KAFKA_CLIENTID: 'rpconsole;broker_count=1;host_override=tansu'
      SCHEMAREGISTRY_ENABLED: true
      SCHEMAREGISTRY_URLS: https://demo.buf.dev/integrations/confluent/bufstream-demo
      ## Enables Protobuf deserialization
      KAFKA_PROTOBUF_ENABLED: 'true'
      ## Instructs the console to use the Schema Registry rather than the local filesystem for deserialization
      KAFKA_PROTOBUF_SCHEMAREGISTRY_ENABLED: true
      ## Provides an interval to refresh schemas from the schema registry.
      KAFKA_PROTOBUF_REFRESHINTERVAL: 5m
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      tansu:
        condition: service_healthy
```

**Comment by xmlking** [comment]
> hi [@xmlking](https://github.com/xmlking),
> 
> I can add a health check to tansu. I've not tried running red panda console, so I'm not sure if that is going to work. Tansu should startup (and crash if it can't run) pretty quickly, have you tried removing the "condition: service_healthy"?
> 
> Would it be possible to share the whole compose that you're trying to run? It might be easier to understand some context for me!
> 
> Thanks!

Thanks for building great project. this is true replacement for kafka. 

yes works    after  removing the "condition: service_healthy"

here is the docker compose I am experimenting with 

https://gist.github.com/xmlking/f25c38b296a5ee92900d7984396828e0

**Comment by shortishly** [comment]
Ah, cool! Thanks for sharing your compose. I've been meaning to try out arroyo, lmk how you get along!

**Comment by erikperkins** [comment]
Using `tansu topic list` works as an interim solution
```yaml
services:
  tansu:
  healthcheck:
    test: ["CMD", "/tansu", "topic", "list"]
  ...
```
