### ISSUE TITLE
listNodes - return the expected number of brokers

### ISSUE THREAD

**Issue by streamsend-io** [tansu-io/tansu#51]
Kafka protocol "listNodes" checks if a Kafka cluster has the expected number of brokers - it is used as a healthcheck by all Confluent docker containers.

For example:
/etc/confluent/docker/ensure runs 

```java -cp /usr/share/java/kafka/*:/usr/share/java/cp-base-new/* -Dlog4j.configuration=file:/etc/cp-base-new/log4j.properties io.confluent.admin.utils.cli.KafkaReadyCommand 1 30 --config /etc/confluent-control-center/admin.properties -b tansu:9092
```

The expected behaviour for the above command is to return "1", indicating one broker.
The actual behaviour is
```
Error while getting broker list.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2005)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:147)
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:149)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
Expected 1 brokers but found only 0. Brokers found [].
```

**Comment by shortishly** [comment]
could you please try adding the following environment to the Tansu compose.yaml to enable more logging:

```
RUST_BACKTRACE=full
RUST_LOG=warn,tansu_storage=debug,tansu_server=debug
```

You can ignore the "warn" bit, but the remainder enables debug logging on the storage and server layers. If you can send me the log I can see what calls are being made.

I tried running:

```
docker run -t -i --rm confluentinc/cp-enterprise-control-center /bin/bash
```

With:

```
java -cp /usr/share/java/kafka/*:/usr/share/java/cp-base-new/* -Dlog4j.configuration=file:/etc/cp-base-new/log4j.properties io.confluent.admin.utils.cli.KafkaReadyCommand 1 30 --config /etc/confluent-control-center/admin.properties -b tansu:9092
```

It complained about the configuration files missing. Is there another container that I should try instead?

**Comment by streamsend-io** [comment]
Yes; the cmd line requires some more config: instead you can create this additional "compose.override.yml" and then "docker-compose up" to start the C3 container too:
```
---
services:
  c3:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    ports:
      - "9021:9021"
    depends_on:
      - tansu
    links:
      - tansu
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "tansu:9092"
      CONTROL_CENTER_ID: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 104857600
      CONTROL_CENTER_DEPRECATED_VIEWS_ENABLE: "true"
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
    command:
      - bash
      - -c
      - |
        sleep 10
        /etc/confluent/docker/run
```

I dont know how to interpret the broker calls (I dont see a "ListNodes") - the debug log is attached.
[docker-compose-up.txt](https://github.com/user-attachments/files/17110862/docker-compose-up.txt)

**Comment by streamsend-io** [comment]
edited to add the ten-second healthcheck timeout - easier debugging...

**Comment by shortishly** [comment]
thanks very much for this, 2 issues identified:

1. The Tansu broker metadata response was returning the broker address as "0.0.0.0" (the listener address), but needed to use the advertised address of of the broker. I've added a new command line parameter of `--kafka-advertised-listener-url`.  Which I think was causing timeout on the kafka ready command. (commit: e5c16fbc05744d4d4150f10422495f0e8b0be072).
2. Requesting topic metadata for an unknown topic was also causing a SQL fault, which now correctly returns "no such topic" error instead. (commit: ca3b3dfbd44b9a12a2ecc60acdc14255e566905c).

Please change your tansu stanza to include:

```
    command: 
      ...
      --kafka-listener-url tcp://0.0.0.0:9092/
      --kafka-advertised-listener-url tcp://tansu:9092/
      ...
```

The above will listen on all interfaces, but will advertise the tansu host in the broker metadata.

I'll merge these changes into main so that a new docker image can be built

**Comment by streamsend-io** [comment]
Thank you. Confirmation that addition of kafka-advertised-listener-url resolves the connectivity issue (and the listNodes error).

Revised docker-compose.yaml and docker-override.yml:
```
---
services:
  db:
    image: postgres:16.4
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    command: -c wal_level=logical
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./work-dir/initdb.d/:/docker-entrypoint-initdb.d/
      - ./work-dir/data:/mnt
    #healthcheck:
    #  test: /usr/bin/pg_isready
    #  interval: 60s
    #  timeout: 10s
    #  retries: 5
    pull_policy: missing

  tansu:
    image: ghcr.io/tansu-io/tansu
    restart: unless-stopped
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info
    command:
      --kafka-cluster-id RvQwrYegSUCkIPkaiAZQlQ
      --kafka-listener-url tcp://tansu:9092/
      --kafka-advertised-listener-url tcp://tansu:9092/
      --kafka-node-id 4343
      --raft-listener-url tcp://0.0.0.0:4567/
      --raft-peer-url tcp://127.0.0.1:4568/
      --storage-engine db=postgres://postgres:postgres@db
      --work-dir /data
    volumes:
      - raft:/data
    ports:
      - 9092:9092
      - 4567:4567
    links:
      - db
    pull_policy:
      ${PULL_POLICY:-always}
volumes:
  db:
    driver: local
  raft:
    driver: local
  c3:
    driver: local
```


docker-override.yml:
```
---
services:
  c3:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    ports:
      - "9021:9021"
    depends_on:
      - tansu
    links:
      - tansu
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "tansu:9092"
      CONTROL_CENTER_STREAMS_CPRESTPROXY_BOOTSTRAP_SERVERS: "tansu:9092"
      CONTROL_CENTER_ID: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 104857600
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
      CONTROL_CENTER_CUB_KAFKA_TIMEOUT: 10
    command:
      - bash
      - -c
      - |
        sleep 5
        /etc/confluent/docker/run
```
